### PR TITLE
Microsite test

### PR DESCRIPTION
**Pull request by agentrickard**
## Asana Ticket(s)
- See ticket [Determine Sub-theme render options](https://app.asana.com/0/1174970560648905/1194057934900278/f).

## Description

- Sets up a taxonomy for use as the sub-theme indicator.

## Testing instructions

- Run `composer install` from the project root.
- Run `../scripts/refresh.sh` or `../scripts/setup.sh` depending on whether you want a new build or not.
- You should have:

  - 2 images (in /web/sites/default/files/2020-10/)
  - 2  media items that contain those images
  - 2 Taxonomy terms in the 'school' vocabulary
  - 1 Article node assigned to the school vocabulary.
  - 1 Views page node assigned to the school vocabulary.

## Remaining Tasks

- [x] Figure out how we import default taxonomies here.
- [x] Figure out how to set the taxonomy context for pages that are not node -- e.g. Views. It may be that we *always* embed Views within node pages to get around this issue.

### CODE REVIEW

**Comment by CocoaBean5** [comment]
I followed your testing steps, and it worked well - 
Screen Shot 2020-10-01 at 11 10 41 AM

**Comment by CocoaBean5** [comment]
Something like this:
```
use Drupal\taxonomy\Entity\Term;

function THEME_NAME_theme_suggestions_page_alter(&$suggestions, &$vars) {
  if (\Drupal::routeMatch()->getRouteName() == 'entity.taxonomy_term.canonical' && $tid = \Drupal::routeMatch()->getRawParameter('taxonomy_term')) {
    $term = Term::load($tid);
    $suggestions[] = 'page__taxonomy__' . $term->getVocabularyId();
  }
}
```
to create html / page template suggestions to create different templates and CSS to go with it might be something we can use.

**Comment by agentrickard** [comment]
This is now working to add default content to the site.

To test that, either run the `setup,sh` or `refresh.sh` scripts. You should have:

- 2 images (in /web/sites/default/files/2020-10/)
- 2 media items that contain those images
- 2 Taxonomy terms in the 'school' vocabulary
- 1 Article node assigned to the `school` vocabulary.
- 1 Views page node assigned to the `school` vocabulary.

**Comment by agentrickard** [comment]
This latest piece adds the `Views Reference` module to allow embedded views in Nodes.

**Comment by CocoaBean5** [comment]
After following your instructions, I see: 

- Two images (logos) in the directory & in Media
- taxonomy terms
- an article and a view page

Everything looks good!

**Pull request merged**
