### PR TITLE
Drupal components styleguide

### PR DESCRIPTION
**Pull request by CocoaBean5**
## Description
- Adds Drupal components scss
- Fixes font paths so it applies on Drupal
- File structure reorg to remove errors on `npm start`
- Moved "Tabs block to above page title, and they should be rendering as tabs instead of list items.
Screen Shot 2020-09-25 at 3 49 27 PM

## Testing instructions
- `ddev start`
- (on a separate terminal window) Navigate to `web/themes/custom/bglobal`, `npm start`. Confirm that the yellow error lines that were present before are no longer there.
- Open a local Drupal page. Check that correct fonts are applying.
- Check that the admin actions tabs are rendering as a horizontal line of tabs.

### CODE REVIEW

**Comment by agentrickard** [comment]
I am getting 404 for all pages in the styleguide. Do I have to rebuild `node_modules` again?

**Comment by agentrickard** [comment]
Rebuilding node packages does not fix the issue. My styleguide is running on port 3002.

```
Pattern Lab is watching for changes to files under ./source/
[17:20:01] Finished 'watchPatternlab' after 184 ms
[17:20:01] Starting 'serve'...
[17:20:01] Finished 'serve' after 10 ms
[17:20:01] Starting 'watchFiles'...
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:3002
    External: http://10.0.1.6:3002
 ----------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 ----------------------------------
[Browsersync] Serving files from: ./public/
[Browsersync] Watching files...
[Browsersync] Reloading Browsers... (buffered 81 events)
```

**Comment by agentrickard** [comment]
My page works in Drupal though.

Screen Shot 2020-09-25 at 5 22 05 PM

**Comment by CocoaBean5** [comment]
@agentrickard I have created placeholder files for the components without anything in them - it was causing npm error. Let me know if this removes your 404 pages.

**Comment by tboggia** [comment]
I'm also having trouble with this one. I'm getting 404 on Patternlab and "Cannot read property 'render' of undefined.
image

I tried: 
Running setup.sh, composer install, and deleting and re-initializing node_modules.

**Comment by tboggia** [comment]
This pull request worked for me!

**Comment by agentrickard** [comment]
This is all working as expected now.

**Pull request merged**
