### PR TITLE
Drupal install

### PR DESCRIPTION
**Pull request by agentrickard**
This PR builds on work in #1 and installs the Drupal site.

See the instructions in the README for this branch.

To test:

-- Follow the `New Installations` instructions.
-- After install, try changing a configuration, then run `drush cex`
-- Run `git status` and confirm a config change in `/config/drupal`
-- Run `git stash` to remove your config change.
-- Run `drush cim` to reset config.

### CODE REVIEW

**Review by CocoaBean5 — COMMENTED** [review]
@agentrickard I have reviewed this branch - I ran `ddev start`, `ddev ssh`, `composer install`, and the local site came up smoothly.

However, on `drush cim`, this is what I got:
Screen Shot 2020-09-16 at 5 10 22 PM

**Comment by CocoaBean5** [comment]
@agentrickard Do you want me to add the whole ddev google doc into the readme `See the DDEV Instructions for setup` section? Or just link it?

**Comment by agentrickard** [comment]
@CocoaBean5 Did you run the "New Installation" process?

## New Installations

From your host machine
- `cd global`
- `ddev start`
- `ddev ssh` -- You might open this in a new terminal tab.

You should now be in the DDEV virtual machine at the prompt:

`USERNAME@global-web:/var/www/html/web$`

Run the following commands.
- `cp ../config/settings/settings.ddev.php sites/default`
- `drush si --existing-config`
- Then note the password given at the end of installation.

**Comment by CocoaBean5** [comment]
Tested the config export / import:
Screen Shot 2020-09-17 at 11 35 07 AM
Screen Shot 2020-09-17 at 11 34 20 AM

Looks good!

**Pull request merged**
