### PR TITLE
Pantheon deploy

### PR DESCRIPTION
**Pull request by agentrickard**
## Asana Ticket(s)
- See ticket [Pantheon configuration testing](https://app.asana.com/0/1174970560648905/1194174850852899/f).

## Description

Enables a build of the site to be pushed to Pantheon as a deployment.

## Testing instructions
1. Checkout this branch
1. Run `composer install` from the project root.
2. Open the README and read the `Deploying to Pantheon` section.
3. Setup `terminus`, `drush` and `ssh` as described in the documentation
4. Build an artifact according to the documentation.
5. Go to https://deploy-berkeleyglobal.pantheonsite.io/ and confirm that the site functions.
6. Go to the Pantheon dashboard DEV site and merge the `deploy` environment
7. Go to https://dev-berkeleyglobal.pantheonsite.io/ and confirm that the site functions.

## Advanced testing

1. After doing the above, run `phing artifact -Dartifact.git.remote_branch=mytest`
1. Approve the deployment
1. Go to the Pantheon Multidev dashboard and Create an environment fo `mytest`
1. Go to https://mytest-berkeleyglobal.pantheonsite.io/ and confirm that the site functions.

## Remaining tasks
- [x] Confirm workflow needs for deployments
- [x] Add HTAUTH security to the Pantheon sites
- [ ] Upgrade the sandbox site

### CODE REVIEW

**Comment by agentrickard** [comment]
Changes successfully deployed to https://mytest-berkeleyglobal.pantheon.berkeley.edu/ -- this should be working as expected.

I deprecated the `/scripts` folder. Now we install with `phing install` and import changes with `phing reload`.

**Comment by tboggia** [comment]
I'll keep trying, but ran into these issues:
- `phing install` results in the following error:
   ```
      html > mkdir:
         [echo] web/profiles/custom
         [foreach] /var/www/html/vendor/palantirnet/the-build/targets/the-build.xml:180:29:
            /var/www/html/vendor/palantirnet/the-build/targets/the-build.xml:180:29: 
            Directory /var/www/html/web/profiles/custom creation was not successful for an unknown reason
      BUILD FAILED
      /var/www/html/build.xml:29:74: Execution of the target buildfile failed. Aborting.
      Total time: 0.3992 seconds
   ```

** UPDATE **
Running `chmod` on the profiles folder advanced it a little bit, but now have this error:
```

BUILD FAILED
IOException: FileSystem::chmod() FAILED. Cannot chmod /var/www/html/web/sites/default. Mode 750. in /var/www/html/vendor/phing/phing/classes/phing/system/io/FileSystem.php:621
Stack trace:
#0 /var/www/html/vendor/phing/phing/classes/phing/system/io/PhingFile.php(956): FileSystem->chmod('/var/www/html/w...', 488)
#1 /var/www/html/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(211): PhingFile->setMode(488)
#2 /var/www/html/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(165): ChmodTask->chmodFile(Object(PhingFile), 488)
#3 /var/www/html/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(118): ChmodTask->chmod()
#4 /var/www/html/vendor/phing/phing/classes/phing/UnknownElement.php(100): ChmodTask->main()
#5 /var/www/html/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#6 /var/www/html/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#7 /var/www/html/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#8 /var/www/html/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#9 /var/www/html/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('install')
#10 /var/www/html/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#11 /var/www/html/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#12 /var/www/html/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#13 /var/www/html/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#14 /var/www/html/vendor/phing/phing/bin/phing(14): require_once('/var/www/html/v...')
#15 {main}
Total time: 0.3722 seconds
#15 {main}FileSystem::chmod() FAILED. Cannot chmod /var/www/html/web/sites/default. Mode 750.
```

Am I supposed to run this from outside the VM?

**Comment by agentrickard** [comment]
These get run from inside the VM. Not from `web` -- I added that to the Troubleshooting docs this morning.

`cd /var/www/html`
`phing` -- get list of phing commands
`phing install`

If you are still running into permissions issues, we'll have to troubleshoot that separately.

**Comment by agentrickard** [comment]
Here's what the permissions on `/web/sites` look like on my host machine:

```
-rw-r--r--   1 rickard  staff   515 Sep 16 13:30 README.txt
drwxr-x---  13 rickard  staff   416 Oct 28 13:15 default
-rw-r--r--   1 rickard  staff   310 Oct 26 10:27 development.services.yml
-rw-r--r--   1 rickard  staff  5749 Sep 17 14:12 example.settings.local.php
-rw-r--r--   1 rickard  staff  2363 Sep 17 14:12 example.sites.php
```

**Comment by tboggia** [comment]
This is my `web/sites`.
```
total 36
drwxrwxrwx  9 Tommaso Tommaso  288 Oct 20 19:09 .
drwxr-xr-x 22 Tommaso Tommaso  704 Oct 28 17:34 ..
-rwxrwxrwx  1 Tommaso Tommaso 8196 Oct 20 17:42 .DS_Store
-rwxrwxrwx  1 Tommaso Tommaso   25 Sep 22 17:38 .gitignore
-rwxrwxrwx  1 Tommaso Tommaso  515 Sep 21 21:16 README.txt
drwxr-x--- 11 Tommaso Tommaso  352 Oct 28 17:34 default
-rwxrwxrwx  1 Tommaso Tommaso  363 Oct 28 18:59 development.services.yml
-rwxrwxrwx  1 Tommaso Tommaso 5749 Sep 21 21:13 example.settings.local.php
-rwxrwxrwx  1 Tommaso Tommaso 2363 Sep 21 21:13 example.sites.php
```

I tried sudo chmod for the defaults folder outside of the VM and got this 
```
  tboggia @ 11:19:38: ~/Sites/global$ chmod -R 777 web/sites
  chmod: Unable to change file mode on web/sites/default/files/2020-09/sandra-lew-170x180-EEE.jpg: Operation not 
  permitted
```
on a bunch of files in the files directory. I'll keep trying things

**Comment by agentrickard** [comment]
That suggests an ownership issue, requiring `sudo` to change perms on those files. Those are probably file uploads belonging to the webserver, which likely isn';t running as you or in your group.

Anything I upload looks the same:

```
-rw-rw-r--  1 rickard  staff  2189590 Oct 28 15:57 IMG_8957.png
-rw-rw-r--  1 rickard  staff     8976 Oct 26 10:37 bglobal-temp-logo.png
-rw-rw-r--  1 rickard  staff     8976 Oct 28 13:08 bglobal-temp-logo_0.png
-rw-rw-r--  1 rickard  staff     2136 Oct 22 15:26 generateImage_TyNC4Q.gif
-rw-rw-r--  1 rickard  staff      984 Oct 23 10:10 generateImage_V2w6M9.png
-rw-rw-r--  1 rickard  staff      589 Oct 22 15:14 generateImage_jWVhor.png
-rw-rw-r--  1 rickard  staff    10450 Oct 26 10:37 hass-temp-logo.png
-rw-rw-r--  1 rickard  staff    10450 Oct 28 13:08 hass-temp-logo_0.png
```

**Comment by tboggia** [comment]
I just did a full delete of the global folder, went through the steps, and got the same first error.

**Comment by agentrickard** [comment]
We don't need that profiles directory, so I removed it. Try again.

**Comment by tboggia** [comment]
Made it through there, now getting the `BUILD FAILED IOException: FileSystem::chmod() FAILED` [error](https://github.com/UC-Berkeley-Extension/global/pull/40#issuecomment-718117139)
```
ls -al /var/www/html/web/sites/default
total 60
drwxrwxrwx 8 Tommaso Tommaso   256 Oct 28 20:05 .
drwxrwxrwx 8 Tommaso Tommaso   256 Oct 28 20:04 ..
-rw-rw-rw- 1 Tommaso Tommaso   188 Oct 28 20:04 .gitignore
-rw-rw-rw- 1 Tommaso Tommaso  6762 Oct 28 20:04 default.services.yml
-rw-rw-rw- 1 Tommaso Tommaso 30891 Oct 28 20:04 default.settings.php
-rw-r--r-- 1     501 Tommaso  2214 Oct 28 20:58 settings.ddev.php
-rw-rw-rw- 1 Tommaso Tommaso  6945 Oct 28 20:04 settings.pantheon.php
-rw-rw-rw- 1 Tommaso Tommaso   249 Oct 28 20:04 settings.php
```

**Comment by agentrickard** [comment]
I really don't know how to debug perms on your machine. Here is looks like `phing` isn't running as you?

**Comment by agentrickard** [comment]
This is what I have:

```
-rw-r--r--   1 rickard  staff   6762 Sep 17 14:12 default.services.yml
-rw-r--r--   1 rickard  staff  30891 Sep 17 14:12 default.settings.php
-rw-r--r--   1 rickard  staff    363 Oct 26 10:37 development.services.yml
drwxr--r--  13 rickard  staff    416 Oct 28 13:07 files
-rw-r--r--   1 rickard  staff    135 Oct 28 13:15 services.build.yml
-rw-r--r--   1 rickard  staff   2214 Oct 28 13:15 settings.build.php
-rw-r--r--@  1 rickard  staff   2214 Oct 26 10:28 settings.ddev.php
-rw-r--r--@  1 rickard  staff   6945 Oct 26 14:55 settings.pantheon.php
-rw-r--r--@  1 rickard  staff    249 Oct  5 14:01 settings.php
```

**Comment by tboggia** [comment]
> I really don't know how to debug perms on your machine. Here is looks like `phing` isn't running as you?

When I suppress (comment out) the FileSystem.php:621 exception, I get more permissions issues downstream:
image

I tried to run some commands to figure out who the commands are running as, but they mostly come back blank, I'm  not sure these are the commands that would be useful here.
image
whoami says Tommaso on the virtual but tboggia on the host.
image

We can do some screenshare debugging tomorrow during scrum.

**Comment by agentrickard** [comment]
I suspect this is all about permission groups, but that is not my area of expertise. I also wonder if its still about git file permissions (https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes)

No scrum on Thursdays, but I am basically free until 11 PT.

**Pull request merged**
